"""
Coordinate Mapping Utilities for HW2

This module provides utilities to convert between different coordinate systems:
- Point cloud coordinates (normalized)
- Habitat coordinates (meters)
- Map pixel coordinates

Essential for Part 3!
"""

import numpy as np


class CoordinateMapper:
    """
    Handles conversion between Habitat coordinates and map pixel coordinates.
    """
    
    def __init__(self, x_min, x_max, z_min, z_max, map_width_pixels=1000):
        """
        Initialize the coordinate mapper.
        
        Args:
            x_min, x_max: Habitat X coordinate range (meters)
            z_min, z_max: Habitat Z coordinate range (meters)
            map_width_pixels: Desired width of the map in pixels
        """
        self.x_min = x_min
        self.x_max = x_max
        self.z_min = z_min
        self.z_max = z_max
        
        # Calculate scale factor (pixels per meter)
        self.x_range = x_max - x_min
        self.z_range = z_max - z_min
        self.scale = map_width_pixels / self.x_range
        
        # Calculate map dimensions
        self.map_width = map_width_pixels
        self.map_height = int(self.z_range * self.scale)
        
        print(f"Coordinate Mapper Initialized:")
        print(f"  Habitat X range: [{x_min:.2f}, {x_max:.2f}] m ({self.x_range:.2f} m)")
        print(f"  Habitat Z range: [{z_min:.2f}, {z_max:.2f}] m ({self.z_range:.2f} m)")
        print(f"  Scale: {self.scale:.2f} pixels/meter")
        print(f"  Map size: {self.map_width} x {self.map_height} pixels")
    
    def habitat_to_pixel(self, x_habitat, z_habitat):
        """
        Convert Habitat coordinates to map pixel coordinates.
        
        Args:
            x_habitat: X coordinate in Habitat (meters)
            z_habitat: Z coordinate in Habitat (meters)
        
        Returns:
            (x_pixel, z_pixel): Pixel coordinates
        """
        x_pixel = int((x_habitat - self.x_min) * self.scale)
        z_pixel = int((z_habitat - self.z_min) * self.scale)
        return x_pixel, z_pixel
    
    def pixel_to_habitat(self, x_pixel, z_pixel):
        """
        Convert map pixel coordinates to Habitat coordinates.
        
        Args:
            x_pixel: X coordinate in pixels
            z_pixel: Z coordinate in pixels
        
        Returns:
            (x_habitat, z_habitat): Habitat coordinates (meters)
        """
        x_habitat = x_pixel / self.scale + self.x_min
        z_habitat = z_pixel / self.scale + self.z_min
        return x_habitat, z_habitat
    
    def is_valid_pixel(self, x_pixel, z_pixel):
        """
        Check if pixel coordinates are within map bounds.
        """
        return (0 <= x_pixel < self.map_width and 
                0 <= z_pixel < self.map_height)
    
    def is_valid_habitat(self, x_habitat, z_habitat):
        """
        Check if Habitat coordinates are within map bounds.
        """
        return (self.x_min <= x_habitat <= self.x_max and 
                self.z_min <= z_habitat <= self.z_max)


def load_mapping_info(filepath='semantic_3d_pointcloud/mapping_info.npy'):
    """
    Load the mapping information generated by semantic_map.py
    
    Returns:
        mapping_info: Dictionary with coordinate ranges
    """
    mapping_info = np.load(filepath, allow_pickle=True).item()
    return mapping_info


def create_mapper_from_file(filepath='semantic_3d_pointcloud/mapping_info.npy', 
                            map_width_pixels=1000):
    """
    Create a CoordinateMapper from saved mapping info.
    
    Args:
        filepath: Path to mapping_info.npy
        map_width_pixels: Desired map width in pixels
    
    Returns:
        CoordinateMapper instance
    """
    info = load_mapping_info(filepath)
    return CoordinateMapper(
        info['x_min'], info['x_max'],
        info['z_min'], info['z_max'],
        map_width_pixels
    )


def point_cloud_to_habitat(points):
    """
    Convert point cloud coordinates to Habitat coordinates.
    
    Args:
        points: (N, 3) array in point cloud coordinates
    
    Returns:
        habitat_points: (N, 3) array in Habitat coordinates (meters)
    """
    return points * 10000.0 / 255.0


def habitat_to_point_cloud(habitat_points):
    """
    Convert Habitat coordinates back to point cloud coordinates.
    
    Args:
        habitat_points: (N, 3) array in Habitat coordinates (meters)
    
    Returns:
        points: (N, 3) array in point cloud coordinates
    """
    return habitat_points * 255.0 / 10000.0


# Example usage
if __name__ == '__main__':
    print("="*60)
    print("COORDINATE MAPPING EXAMPLE")
    print("="*60)
    
    # Example: Load mapping info from saved file
    try:
        info = load_mapping_info()
        print("\nLoaded mapping information:")
        for key, value in info.items():
            print(f"  {key}: {value:.3f}")
        
        # Create mapper
        mapper = create_mapper_from_file(map_width_pixels=1000)
        
        print("\n" + "="*60)
        print("CONVERSION EXAMPLES")
        print("="*60)
        
        # Example conversions
        test_coords = [
            (0.0, 0.0),      # Origin
            (5.0, 3.0),      # Arbitrary point
            (-2.0, -1.5),    # Negative coordinates
        ]
        
        for x_h, z_h in test_coords:
            x_p, z_p = mapper.habitat_to_pixel(x_h, z_h)
            x_h_back, z_h_back = mapper.pixel_to_habitat(x_p, z_p)
            
            print(f"\nHabitat ({x_h:.2f}, {z_h:.2f}) m")
            print(f"  → Pixel ({x_p}, {z_p})")
            print(f"  → Back to Habitat ({x_h_back:.2f}, {z_h_back:.2f}) m")
            print(f"  Valid: {mapper.is_valid_habitat(x_h, z_h)}")
        
        print("\n" + "="*60)
        print("Point Cloud to Habitat Conversion Example")
        print("="*60)
        
        # Example point cloud coordinates
        pc_coords = np.array([[128.0, 64.0, 200.0]])
        habitat_coords = point_cloud_to_habitat(pc_coords)
        
        print(f"\nPoint cloud coords: {pc_coords[0]}")
        print(f"Habitat coords: {habitat_coords[0]}")
        print(f"Scale factor: {10000.0 / 255.0:.4f}")
        
    except FileNotFoundError:
        print("\n❌ mapping_info.npy not found!")
        print("   Please run semantic_map.py first to generate the mapping information.")
        print("\n   Example: python semantic_map.py")
        
    print("\n" + "="*60)
